runtime: python39
entrypoint: gunicorn -b ":$PORT" --timeout 120 --graceful-timeout 120 --workers 1 run:app
instance_class: F2

service: default

env_variables:
  GAE_ENV: 'standard'
  PYTHONUNBUFFERED: 'true'
  FLASK_APP: run.py
  FLASK_ENV: production

beta_settings:
  cloud_sql_instances: prompt-wizards:europe-west1:leaderboard-db

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
  min_idle_instances: 1
  max_concurrent_requests: 50

readiness_check:
  app_start_timeout_sec: 1200
  check_interval_sec: 30
  failure_threshold: 3
  success_threshold: 2
  timeout_sec: 60

liveness_check:
  initial_delay_sec: 1200
  check_interval_sec: 30
  timeout_sec: 60

handlers:
  - url: /.*
    script: auto
    secure: always