"""Initial migration

Revision ID: 0526045be1bd
Revises: 
Create Date: 2024-11-19 11:05:47.635746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0526045be1bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('prompt_length', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('word_accuracy', sa.Float(), nullable=True),
    sa.Column('efficiency', sa.Float(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('length_penalty_avg', sa.Float(), nullable=True),
    sa.Column('prompt_efficiency', sa.Float(), nullable=True),
    sa.Column('base_accuracy', sa.Float(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('is_production', sa.Boolean(), nullable=True),
    sa.Column('raw_predictions', sa.JSON(), nullable=True),
    sa.Column('inputs_used', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leaderboard_entry')
    # ### end Alembic commands ###
